name: Publish

on:
  push:
    branches: [ master ]

jobs:    
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: source/DependencyInjectionExtensions/DependencyInjectionExtensions.csproj
          PACKAGE_NAME: Nricher.DependencyInjectionExtensions
          VERSION_STATIC: ${{ steps.get_version.outputs.version }}
          NUGET_KEY: ${{secrets.NRICHER_NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
